task_name: long_term_forecast
root_path: ./dataset/custom/
data_path: dataset-h_43800-n_0.0-b_True.csv
model: TimeXer
features: MS
target: load
seq_len: 48
label_len: 12
pred_len: 24
d_model: 128
n_heads: 1
e_layers: 1
d_ff: 128
n_vars_bool: 1
n_vars_num: 3
n_vars_time_features: 4
dropout: 0.0
use_norm: 0
train_epochs: 100
batch_size: 256
freq: h
use_boolean: False
use_learnable_combination: False
use_flatten_head: True
use_attention: True
use_cross: True
log_to_comet: True
log_interval: 120
boolean_cols:
  - 'bool_day'