task_name: long_term_forecast
root_path: ./dataset/custom/
data_path: dataset2.csv
model: TimeXer
features: MS
target: load
seq_len: 24
label_len: 12
pred_len: 24
d_model: 32
n_heads: 1
e_layers: 1
d_ff: 128
dropout: 0.0
use_norm: 0
train_epochs: 5
batch_size: 16
freq: h
use_boolean: False
use_learnable_combination: False
use_flatten_head: False
use_attention: False
use_cross: False
boolean_cols:
  - 'bool_day'