task_name: long_term_forecast
root_path: ./dataset/custom/
data_path: dataset2.csv
model: TimeXer
features: MS
target: load
seq_len: 128
label_len: 12
pred_len: 24
d_model: 32
n_heads: 1
e_layers: 5
d_ff: 128
n_vars_bool: 1
n_vars_num: 3
n_vars_time_features: 4
dropout: 0.0
use_norm: 0
train_epochs: 5
batch_size: 5
freq: h
use_boolean: False
use_learnable_combination: False
use_flatten_head: True
use_attention: True
use_cross: False
boolean_cols:
  - 'bool_day'